# Generated by Django 5.2.5 on 2025-08-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_principal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosImportados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_giant', models.CharField(max_length=255)),
                ('mawb', models.CharField(blank=True, max_length=255, null=True)),
                ('hawb', models.CharField(blank=True, max_length=255, null=True)),
                ('q', models.CharField(blank=True, max_length=255, null=True)),
                ('c3', models.CharField(blank=True, max_length=255, null=True)),
                ('deliveryid', models.CharField(blank=True, max_length=255, null=True)),
                ('sostatus_releasedonholdreturned', models.CharField(blank=True, max_length=255, null=True)),
                ('data_liberacao', models.DateField(blank=True, null=True)),
                ('cipbrl', models.CharField(blank=True, max_length=255, null=True)),
                ('pc', models.CharField(blank=True, max_length=255, null=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('peso_cobravel', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tipo', models.CharField(blank=True, max_length=255, null=True)),
                ('pupdt', models.DateField(blank=True, null=True)),
                ('ciok', models.DateField(blank=True, null=True)),
                ('lientrydt', models.DateField(blank=True, null=True)),
                ('liok', models.DateField(blank=True, null=True)),
                ('ok_to_ship', models.CharField(blank=True, max_length=255, null=True)),
                ('li', models.CharField(blank=True, max_length=255, null=True)),
                ('hawbdt', models.DateField(blank=True, null=True)),
                ('estimatedbookingdt', models.DateField(blank=True, null=True)),
                ('arrivaldestinationdt', models.DateField(blank=True, null=True)),
                ('solicitacao_fundos', models.CharField(blank=True, max_length=255, null=True)),
                ('fundos_recebidos', models.CharField(blank=True, max_length=255, null=True)),
                ('eadidt', models.DateField(blank=True, null=True)),
                ('diduedt', models.DateField(blank=True, null=True)),
                ('diduenumber', models.CharField(blank=True, max_length=255, null=True)),
                ('icmspago', models.DateField(blank=True, null=True)),
                ('canal_cor', models.CharField(blank=True, max_length=255, null=True)),
                ('data_liberacao_ccr', models.DateField(blank=True, null=True)),
                ('data_nfe', models.DateField(blank=True, null=True)),
                ('numero_nfe', models.CharField(blank=True, max_length=255, null=True)),
                ('nftgdt', models.DateField(blank=True, null=True)),
                ('nftg', models.CharField(blank=True, max_length=255, null=True)),
                ('dlvatdestination', models.DateField(blank=True, null=True)),
                ('status_impexp', models.CharField(blank=True, max_length=255, null=True)),
                ('data_estimada', models.DateField(blank=True, null=True)),
                ('eventos', models.TextField(blank=True, null=True)),
                ('real_lead_time', models.CharField(blank=True, max_length=255, null=True)),
                ('ship_failure_days', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_justificativa_atraso', models.CharField(blank=True, max_length=255, null=True)),
                ('justificativa_atraso', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
