# Generated by Django 5.2.5 on 2025-08-15 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_principal', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dadosimportados',
            table='dados_importados',
        ),
    ]
